### ISSUE TITLE
not every item is available.

### ISSUE THREAD

**Issue by lampje25** [Chouffy/home_assistant_tgtg#45]
The problem is that not every tgtg item is available.
Below is the error message in the log:

Logger: homeassistant.components.sensor
Source: custom_components/tgtg/sensor.py:186
Integration: Sensor (documentation, issues)
First occurred: 11:21:44 (1 occurrences)
Last logged: 11:21:44

Error while setting up tgtg platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tgtg/sensor.py", line 73, in setup_platform
    add_entities([TGTGSensor(each_item_id)])
  File "/config/custom_components/tgtg/sensor.py", line 93, in __init__
    self.update()
  File "/config/custom_components/tgtg/sensor.py", line 186, in update
    self.tgtg_answer = tgtg_client.get_item(item_id=self.item_id)
  File "/usr/local/lib/python3.10/site-packages/tgtg/__init__.py", line 273, in get_item
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (410, b'{"errors":[{"code":"ENTITY_DISABLED","message":"Entity ItemId(56298) is not active"}]}')

**Comment by Chouffy** [comment]
Hi @lampje25 
Based on the last error (ENTITY_DISABLED), I would guess it's on TooGoodToGo side.
Is the item in question still active in the app? Can you see it in your favorites and/or on the map?

**Comment by lampje25** [comment]
Yes they are almost all active.
I reinstalled the favorites list and now it works fine.
Thank you!

**Comment by lampje25** [comment]
So problem solved

**Comment by Chouffy** [comment]
Superb!
