### ISSUE TITLE
Something wrong with the latest update?

### ISSUE THREAD

**Issue by skinkie** [Chouffy/home_assistant_tgtg#52]
I have updated this component via hacs, so I would assume it would be automatic.

But I now get this:
```
Traceback (most recent call last):
  File "/home/skinkie/.local/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/skinkie/.homeassistant/custom_components/tgtg/sensor.py", line 65, in setup_platform
    tgtg_client = TgtgClient(
TypeError: TgtgClient.__init__() got an unexpected keyword argument 'cookie'
```

**Comment by skinkie** [comment]
After manually removing de tgtg dep in the deps folder. That works.

**Comment by swin66** [comment]
Did you run the script to get the new config setting?

**Comment by skinkie** [comment]
Yep. See above :)

**Comment by Chouffy** [comment]
Glad to hear that it worked!
